### ISSUE TITLE
Sensor data over MQTT

### ISSUE THREAD

**Issue by akshithaluguri22** [akshithaluguri22/final-project-AkshithAluguri-Appcode#10]
DOD: Send sensor data over MQTT 

Blockers: None

**Comment by Ruthvik-Chanda** [comment]
Sensor Data that is sent from the Client to the Server

[APP_CODE Repo  Link](https://github.com/akshithaluguri22/final-project-AkshithAluguri-Appcode)
![Image](https://user-images.githubusercontent.com/112532669/235331931-61df5569-6e6f-4182-a622-6de1e2a80ee7.png)
