### ISSUE TITLE
Setup Buildroot Repository for Server

### ISSUE THREAD

**Issue by akshithaluguri22** [akshithaluguri22/final-project-AkshithAluguri-Appcode#2]
DoD: Create a Buildroot setup for server
Blockers: None

**Comment by Ruthvik-Chanda** [comment]
1. Successfully, built the build root image for the Server side, 
2. Flashed and booted up an image for RaspberryPi 3b+

Blockers: Not able to login into the build root.

Repo: (https://github.com/cu-ecen-aeld/final-project-Ruthvik-Chanda/tree/3b9971c57d6ec5ee492318825431a9e4807a2a09)
