### ISSUE TITLE
Humidity Sensor interfacing with Buildroot

### ISSUE THREAD

**Issue by akshithaluguri22** [akshithaluguri22/final-project-AkshithAluguri-Appcode#8]
DoD: Integrating the Humidity sensor with Buildroot.

Blockers: None

**Comment by Ruthvik-Chanda** [comment]
Humidity sensor working on Buildroot.

[Repo  Link](https://github.com/akshithaluguri22/final-project-AkshithAluguri-Appcode)

Issue :  Humidity Sensor Hardware not working !

**Comment by Ruthvik-Chanda** [comment]
Humidty Sensor Working Update 



![Image](https://user-images.githubusercontent.com/112532669/235327657-694a3e5e-ea07-4183-9bbf-54b6a1a8eb55.png)
